# Generated by Django 5.1.6 on 2026-04-10 08:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BuildingProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("published", models.BooleanField(default=False)),
                ("data", models.JSONField()),
                ("info", models.TextField()),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("Chipata", "Chipata"),
                            ("Choma", "Choma"),
                            ("Isoka", "Isoka"),
                            ("Kabompo", "Kabompo"),
                            ("Kafironda", "Kafironda"),
                            ("Kalabo", "Kalabo"),
                            ("Kaoma", "Kaoma"),
                            ("Kasama", "Kasama"),
                            ("Kasempa", "Kasempa"),
                            ("Kawambwa", "Kawambwa"),
                            ("Lundazi", "Lundazi"),
                            ("Magoye", "Magoye"),
                            ("Mansa", "Mansa"),
                            ("Mbala", "Mbala"),
                            ("Mfuwe", "Mfuwe"),
                            ("Misamfu", "Misamfu"),
                            ("Mkushi", "Mkushi"),
                            ("Mongu", "Mongu"),
                            ("Mpika", "Mpika"),
                            ("Msekera", "Msekera"),
                            ("Mumbwa", "Mumbwa"),
                            ("Petauke", "Petauke"),
                            ("Samya", "Samya"),
                            ("Senanga", "Senanga"),
                            ("Serenje", "Serenje"),
                            ("Sesheke", "Sesheke"),
                            ("Solwezi", "Solwezi"),
                            ("Zambezi", "Zambezi"),
                        ],
                        max_length=100,
                    ),
                ),
                ("name", models.TextField()),
                ("uuid", models.TextField()),
            ],
        ),
    ]
