# Generated by Django 5.1.6 on 2026-05-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0003_buildingproject_simulation_results"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildingproject",
            name="location",
            field=models.CharField(
                choices=[
                    ("Chipata", "Chipata"),
                    ("Choma", "Choma"),
                    ("Isoka", "Isoka"),
                    ("Kabompo", "Kabompo"),
                    ("Kabwe", "Kabwe"),
                    ("Kafironda", "Kafironda"),
                    ("Kafue", "Kafue"),
                    ("Kalabo", "Kalabo"),
                    ("Kaoma", "Kaoma"),
                    ("Kasama", "Kasama"),
                    ("Kasempa", "Kasempa"),
                    ("Kawambwa", "Kawambwa"),
                    ("Livingstone", "Livingstone"),
                    ("Lundazi", "Lundazi"),
                    ("Lusaka", "Lusaka"),
                    ("Magoye", "Magoye"),
                    ("Mansa", "Mansa"),
                    ("Mbala", "Mbala"),
                    ("Mfuwe", "Mfuwe"),
                    ("Misamfu", "Misamfu"),
                    ("Mkushi", "Mkushi"),
                    ("Mongu", "Mongu"),
                    ("Mount Makulu", "Mount Makulu"),
                    ("Mpika", "Mpika"),
                    ("Msekera", "Msekera"),
                    ("Mumbwa", "Mumbwa"),
                    ("Petauke", "Petauke"),
                    ("Samya", "Samya"),
                    ("Senanga", "Senanga"),
                    ("Serenje", "Serenje"),
                    ("Sesheke", "Sesheke"),
                    ("Solwezi", "Solwezi"),
                    ("Zambezi", "Zambezi"),
                ],
                max_length=100,
            ),
        ),
    ]
